name: build-and-lint

on:
  push:
    branches: [main, stage]
  pull_request:
    branches: [main, stage]
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  REGISTRY: ghcr.io
  FRONTEND_IMAGE_NAME: ${{ github.repository }}/frontend
  BACKEND_IMAGE_NAME: ${{ github.repository }}/backend

jobs:
  build-and-lint:
    name: build-and-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
         node-version: 20

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run backend lint
        working-directory: ./backend
        run: npm run lint -- --max-warnings=0

      - name: Run frontend lint
        working-directory: ./frontend
        run: npm run lint -- --max-warnings=0

      - name: Set up Node.js for Docker build
        uses: actions/setup-node@v4